repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--disable-rule=terraform_required_providers
          - --args=--disable-rule=terraform_required_version
      #- id: terraform_tfsec
      #- id: terraform_checkov
