name: terraform-lint

on: [push, pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # main
    - name: Lint Terraform
      uses: actionshub/terraform-lint@9e854ecdc0cedda954adfffccced9f71dc12fda0 # main
