name: Generate terraform docs
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the MODULE.md and push changes back to PR branch
      uses: Dirrk/terraform-docs@26b70436ceceba0a62c6b083d67c0796ea89bdeb # v1.0.8
      with:
        tf_docs_working_dir: .
        tf_docs_output_file: MODULE.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'
